CREATE TABLE albums
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number     INTEGER,
    title      VARCHAR(255),
    artist     VARCHAR(255),
    genre      VARCHAR(255),
    sub_genre  VARCHAR(255),
    album_year INTEGER,
    image_link VARCHAR(255)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    user_name     VARCHAR(255),
    user_password VARCHAR(255),
    admin        INTEGER
);
